trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals marjan

variables:
  buildConfiguration: 'Release'

steps:
- task: JenkinsDownloadArtifacts@1
  inputs:
    jenkinsServerConnection: 'jenkinstoken'
    jobName: 'Marjan'
    saveTo: 'jenkinsArtifacts'
    jenkinsBuild: 'LastSuccessfulBuild'

- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: 'insomeaIIS'
    VirtualApplication: 'insomeaIIS'
    Package: '$(System.DefaultWorkingDirectory)\**\jenkinsArtifacts'