trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals marjan

variables:
  buildConfiguration: 'Release'

steps:
- task: JenkinsDownloadArtifacts@1
  inputs:
    jenkinsServerConnection: 'jenkinstoken'
    jobName: 'Marjan'
    saveTo: 'jenkinsArtifacts'
    jenkinsBuild: 'LastSuccessfulBuild'

# IIS web app deploy v0
# Deploy a website or web application using Web Deploy.
- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: DeployementIIS     
    Package: '$(System.DefaultWorkingDirectory)\**\publish' 