trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals marjanIIS

variables:
  buildConfiguration: 'Release'

steps:
- task: JenkinsDownloadArtifacts@1
  inputs:
    jenkinsServerConnection: 'jenkinstoken'
    jobName: 'Marjan'
    saveTo: 'jenkinsArtifacts'
    jenkinsBuild: 'LastSuccessfulBuild'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'DevOps – MPN(e5b2c5cd-7140-4bdb-8452-50a2a89c25d5)'
    appType: 'webApp'
    WebAppName: 'marjan'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'