# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals marjan

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: JenkinsJob
  steps:
  - task: JenkinsQueueJob@1
    inputs:
      serverEndpoint: 'jenkins'
      jobName: 'Marjan'